### PR TITLE
Updated grpc and protobuf for newer bazel versions

### LINKED ISSUE #135: Error at Compass Instalation
The issue tracker is only for reporting bugs or submitting feature requests.
If you need technical assistance for running a node please consult the #fullnode channel on Discord (https://discord.gg/jrxApWC) or https://forum.helloiota.com/Technology/Help.
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
Step 2 of  https://github.com/iotaledger/compass results in error.

### Hardware Spec
On what hardware is the node running on?
Virtual Box running VM Ubuntu 18.04.2 LTS, Memory 3GB, storage 100GB. Host machine Intel i7-6500U CPU @ 2.50GHz, RAM memory 16GB, OS 64bits, with processor x64, Windows 10 Home Single Language.

### Steps To Reproduce
1. Install bazel from https://bazel.build
2. 
[bazel_coordinator_error.txt](https://github.com/iotaledger/compass/files/3414688/bazel_coordinator_error.txt)

3. 

### Expected behaviour
No error in step 2.

### Actual behaviour
Pls see enclosed  file.

### Errors
as in enclosed file:
ubu01@ubu01:~/compass$ bazel run //docker:coordinator
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:69:1: file '//container:layer.bzl' does not contain symbol 'LayerInfo' (did you mean 'layer'?)
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:396:15: Traceback (most recent call last):
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 396
                dict(((((_layer.attrs.items() + {"bas...()))
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 396, in dict
                _layer
global variable '_layer' is referenced before assignment.
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:438:17: Traceback (most recent call last):
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 438
                dict(_layer.outputs)
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 438, in dict
:::::::::::::

*Note*
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
At the end, I wish to run private tangle, as instructed in https://github.com/iotaledger/compass/tree/master/docs/private_tangle
I need to solve coordinator installation.

### Motivation
I need to understand Tangle functionality for my mastership.

### Requirements
Nothing at the moment. Only study issues. 

### Open Questions (optional)
Nothing for the moment.

### Am I planning to do it myself with a PR?
Well. Not know what is PR.

### PR DESCRIPTION
**Pull request by kwek20**
Fixes #135
Tested on bazel 0.28.1 

Updated docker-rules from v0.5.1 to v0.9.0
Updated GRPC from v1.17.2 to v1.23.0
Updated protobuf from v3.6.1.3 to v3.8.0

### CODE REVIEW

**Comment by nelsonchan1996** [comment]
still can't run it:

root@vultr:~/compass# bazel run //docker:layers_calculator
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:69:1: file '//container:layer.bzl' does not contain symbol 'LayerInfo' (did you mean 'layer'?)
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:396:15: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 396
		dict(((((_layer.attrs.items() + {"bas...()))
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 396, in dict
		_layer
global variable '_layer' is referenced before assignment.
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:438:17: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 438
		dict(_layer.outputs)
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 438, in dict
		_layer
global variable '_layer' is referenced before assignment.
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:440:1: global variable '_outputs' is referenced before assignment.
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:443:13: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 442
		struct(attrs = _attrs, outputs = _outputs, ...)
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 443, in struct
		_attrs
global variable '_attrs' is referenced before assignment.
ERROR: /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl:449:13: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 448
		rule(attrs = _attrs, executable = True, o..., ...)
	File "/root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/image.bzl", line 449, in rule
		_attrs
global variable '_attrs' is referenced before assignment.
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/container.bzl: Extension file 'container/image.bzl' has errors
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/506ac1cd9efd19d09d738427a1de2bb4/external/io_bazel_rules_docker/container/container.bzl: Extension file 'container/image.bzl' has errors
INFO: Elapsed time: 0.070s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by kwek20** [comment]
@nelsonchan1996 Could you try and start with a fresh environment? i tested it on your exact bazel version, and it seems to work!

**Comment by kwek20** [comment]
@nelsonchan1996 I confirmed on a new machine this is not yet solved. Ill take a look at it again later

**Comment by karimodm** [comment]
Builds for me now, merging.

**Pull request merged**
